public class Demo01_SimpleMath {

    // This line is a comment :-)

    public Integer numbersMinus(Integer i, Integer j) {
        Integer result = i - j;
        System.debug('i - j => ' + i + ' - ' + j + ' = ' + result);
        return result;
    }

    public Integer numbersPlus(Integer i, Integer j) {
        Integer result = i - j;
        System.debug('i + j => ' + i + ' + ' + j + ' = ' + result);
        return result;
    }
}
